###
GET http://localhost:3001/list-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzIzMTUyMTAsImV4cCI6MTczMjMxODgxMH0.uaA05vi6VD--6BshB0CvctYwpOQVcXPGg06gq-6HZy0

###
POST http://localhost:3001/create-user
Authorization: Bearer mysecretkeyfcbackend
Content-Type: application/json

{
  "username": "dark",
  "password": "darkzinhoRL"
}

###
GET http://localhost:3001/find-user/dark
Authorization: Bearer mysecretkeyfcbackend